import type { Metadata } from "next";
import { Montserrat, Oxanium } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "devstage",
  description: "Generated by create next app",
};

const oxanium = Oxanium({
  weight: ["500", "600"],
  subsets: ["latin"],
  variable: "--font-oxanium",
});

const montserrat = Montserrat({
  weight: ["400", "600"],
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className="antialiased bg-gray-900 bg-gray-100">{children}</body>
    </html>
  );
}
